name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        JEKYLL_ENV: production
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && gem install bundler && bundler install && npm install -g firebase-tools && jekyll build --future && firebase deploy --token=$FIREBASE_TOKEN --non-interactive"
